# Generated by Django 3.1.2 on 2020-11-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201122_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictogram_dpi',
            name='image',
            field=models.ImageField(upload_to='pittogrammi/'),
        ),
        migrations.AlterField(
            model_name='pictogram_h',
            name='image',
            field=models.ImageField(upload_to='pittogrammi/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sds',
            field=models.FileField(blank=True, null=True, upload_to='sds/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tds',
            field=models.FileField(blank=True, null=True, upload_to='tds/'),
        ),
    ]
