# Generated by Django 3.1.2 on 2020-12-20 13:16

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, default=builtins.id, max_length=100),
        ),
    ]
