# Generated by Django 3.1.2 on 2020-12-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201220_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
