# Generated by Django 3.1.2 on 2020-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='concentrazioni',
            field=models.JSONField(default='{}'),
        ),
    ]
