# Generated by Django 3.1.2 on 2020-12-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_concentrazioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='concentrazioni',
            field=models.JSONField(default=dict),
        ),
    ]
