# Generated by Django 3.1.2 on 2020-12-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201228_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year_in_school',
            field=models.CharField(choices=[('ON', 'Attivo'), ('PROVA', 'Prova'), ('OFF', 'Archiviato')], default='PROVA', max_length=10),
        ),
    ]
