# Generated by Django 3.1.2 on 2020-12-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='year_in_school',
            new_name='stato_arte',
        ),
    ]
