# Generated by Django 3.1.2 on 2021-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='conf_zdhc',
            field=models.BooleanField(default=False),
        ),
    ]
