# Generated by Django 3.1.2 on 2021-01-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210106_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='note_zdhc',
        ),
    ]
