# Generated by Django 3.1.2 on 2021-01-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210106_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificazioni',
            field=models.ManyToManyField(blank=True, to='product.Certificazioni'),
        ),
        migrations.AddField(
            model_name='product',
            name='gateway',
            field=models.ManyToManyField(blank=True, to='product.Gateway_zdhc'),
        ),
    ]
