# Generated by Django 3.1.2 on 2021-01-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_sds_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sds_rev',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Revisione'),
        ),
    ]
