# Generated by Django 3.1.2 on 2021-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_product_conf_zdhc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conf_zdhc',
            field=models.CharField(choices=[('SI', 'Conforme'), ('NO', 'Non Conforme'), ('NA', 'NA')], default='NA', max_length=10),
        ),
    ]
